
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
Prisma.prismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.Cuenta_espacioScalarFieldEnum = {
  id_item: 'id_item',
  id_reserva: 'id_reserva',
  nombre_producto: 'nombre_producto',
  cantidad: 'cantidad',
  valor_unitario: 'valor_unitario',
  valor_total: 'valor_total',
  estado: 'estado',
  metodo_pago: 'metodo_pago',
  fecha_registro: 'fecha_registro',
  anotaciones: 'anotaciones'
};

exports.Prisma.Cuenta_personaScalarFieldEnum = {
  id_item_persona: 'id_item_persona',
  id_huesped: 'id_huesped',
  nombre_persona: 'nombre_persona',
  id_reserva: 'id_reserva',
  fecha: 'fecha',
  descripcion: 'descripcion',
  cantidad: 'cantidad',
  valor_unitario: 'valor_unitario',
  valor_total: 'valor_total',
  estado: 'estado',
  metodo_pago: 'metodo_pago',
  fecha_registro: 'fecha_registro'
};

exports.Prisma.EspacioScalarFieldEnum = {
  id_espacio: 'id_espacio',
  numero: 'numero',
  tipo_espacio: 'tipo_espacio',
  tipo_habitacion: 'tipo_habitacion',
  capacidad_personas: 'capacidad_personas',
  precio_persona_1: 'precio_persona_1',
  precio_persona_2: 'precio_persona_2',
  precio_adicional: 'precio_adicional',
  estado_limpieza: 'estado_limpieza',
  activo: 'activo',
  tiene_minibar: 'tiene_minibar'
};

exports.Prisma.HuespedScalarFieldEnum = {
  id_huesped: 'id_huesped',
  nombre_completo: 'nombre_completo',
  telefono: 'telefono',
  documento: 'documento',
  tipo_documento: 'tipo_documento',
  procedencia: 'procedencia',
  firma: 'firma',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.Inventario_minibarScalarFieldEnum = {
  id_inventario: 'id_inventario',
  id_espacio: 'id_espacio',
  nombre_producto: 'nombre_producto',
  cantidad: 'cantidad',
  precio_unitario: 'precio_unitario',
  fecha_vencimiento: 'fecha_vencimiento',
  fecha_actualizacion: 'fecha_actualizacion'
};

exports.Prisma.ReservaScalarFieldEnum = {
  id_reserva: 'id_reserva',
  id_huesped: 'id_huesped',
  id_espacio: 'id_espacio',
  tipo_reserva: 'tipo_reserva',
  dni_tipo: 'dni_tipo',
  check_in: 'check_in',
  check_out: 'check_out',
  cantidad_adultos: 'cantidad_adultos',
  cantidad_ninos: 'cantidad_ninos',
  fecha_evento: 'fecha_evento',
  hora_inicio: 'hora_inicio',
  hora_fin: 'hora_fin',
  estado_reserva: 'estado_reserva',
  monto_total: 'monto_total',
  estado_pago: 'estado_pago',
  metodo_pago: 'metodo_pago',
  monto_pagado: 'monto_pagado',
  anotaciones: 'anotaciones',
  firma: 'firma',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.Configuracion_hotelScalarFieldEnum = {
  id: 'id',
  nombre_hotel: 'nombre_hotel',
  direccion: 'direccion',
  telefono: 'telefono',
  nit: 'nit',
  email: 'email',
  ciudad: 'ciudad',
  hora_check_in: 'hora_check_in',
  hora_check_out: 'hora_check_out',
  fecha_actualizacion: 'fecha_actualizacion'
};

exports.Prisma.Tipo_espacio_configScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  precio_base: 'precio_base',
  recargo_pareja: 'recargo_pareja',
  recargo_adicional: 'recargo_adicional',
  max_personas_adicionales: 'max_personas_adicionales'
};

exports.Prisma.Categoria_inventarioScalarFieldEnum = {
  id_categoria: 'id_categoria',
  nombre: 'nombre',
  activo: 'activo',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.ProveedorScalarFieldEnum = {
  id_proveedor: 'id_proveedor',
  nombre: 'nombre',
  nit: 'nit',
  telefono: 'telefono',
  email: 'email',
  direccion: 'direccion',
  ciudad: 'ciudad',
  contacto: 'contacto',
  notas: 'notas',
  activo: 'activo',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.Producto_inventarioScalarFieldEnum = {
  id_producto: 'id_producto',
  nombre: 'nombre',
  descripcion: 'descripcion',
  categoria: 'categoria',
  unidad_medida: 'unidad_medida',
  precio_costo: 'precio_costo',
  precio_venta: 'precio_venta',
  stock_actual: 'stock_actual',
  stock_minimo: 'stock_minimo',
  id_proveedor: 'id_proveedor',
  activo: 'activo',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.Movimiento_inventarioScalarFieldEnum = {
  id_movimiento: 'id_movimiento',
  id_producto: 'id_producto',
  tipo: 'tipo',
  motivo: 'motivo',
  cantidad: 'cantidad',
  stock_antes: 'stock_antes',
  stock_despues: 'stock_despues',
  precio_unitario: 'precio_unitario',
  referencia_id: 'referencia_id',
  referencia_tipo: 'referencia_tipo',
  notas: 'notas',
  fecha: 'fecha'
};

exports.Prisma.Gasto_operativoScalarFieldEnum = {
  id_gasto: 'id_gasto',
  categoria: 'categoria',
  descripcion: 'descripcion',
  monto: 'monto',
  fecha: 'fecha',
  comprobante: 'comprobante',
  proveedor_nombre: 'proveedor_nombre',
  es_recurrente: 'es_recurrente',
  dia_recurrente: 'dia_recurrente',
  notas: 'notas',
  activo: 'activo',
  fecha_creacion: 'fecha_creacion'
};

exports.Prisma.Categoria_gastoScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  activo: 'activo'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  cuenta_espacio: 'cuenta_espacio',
  cuenta_persona: 'cuenta_persona',
  espacio: 'espacio',
  huesped: 'huesped',
  inventario_minibar: 'inventario_minibar',
  reserva: 'reserva',
  configuracion_hotel: 'configuracion_hotel',
  tipo_espacio_config: 'tipo_espacio_config',
  categoria_inventario: 'categoria_inventario',
  proveedor: 'proveedor',
  producto_inventario: 'producto_inventario',
  movimiento_inventario: 'movimiento_inventario',
  gasto_operativo: 'gasto_operativo',
  categoria_gasto: 'categoria_gasto'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
